language: swift
osx_image: xcode11.2

xcode_scheme: AutoLayout
xcode_destination: platform=iOS Simulator,OS=13.2,name=iPhone 8

script:
  - set -o pipefail && xcodebuild clean
  - set -o pipefail && xcodebuild -project AutoLayout.xcodeproj -scheme AutoLayout -configuration "Release" -destination "platform=iOS Simulator,name=iPhone 8" | tee raw.txt | xcpretty -c cat raw.txt | ocunit2junit
  - set -o pipefail && xcodebuild test -project AutoLayout.xcodeproj -scheme AutoLayout -configuration "Release" -destination "platform=iOS Simulator,name=iPhone 8" | tee raw.txt | xcpretty -c cat raw.txt | ocunit2junit